### ISSUE TITLE
Downloading folders doesn't work

### ISSUE THREAD

**Issue by Imperial-Guard** [sapk/dockerfiles#43]
I got the following errors while trying to download a workspace folder: 

`
26: Error: spawn zip ENOENT
    at /cloud9/plugins/node_modules/vfs-local/localfs.js:1631:23
    at resolvePath (/cloud9/plugins/node_modules/vfs-local/localfs.js:365:13)
    at Object.spawn (/cloud9/plugins/node_modules/vfs-local/localfs.js:1617:9)
    at Domain.<anonymous> (/cloud9/plugins/node_modules/vfs-local/localfs.js:259:30)
    at Domain.run (domain.js:221:14)
    at Object.api.(anonymous function) [as spawn] (/cloud9/plugins/node_modules/vfs-local/localfs.js:258:23)
    at Worker.wrapped (/cloud9/plugins/node_modules/vfs-socket/worker.js:474:22)
    at Worker.Agent._onMessage (/cloud9/node_modules/smith/smith.js:471:8)
    at emitOne (events.js:96:13)
    at Transport.emit (events.js:188:7)
VFS Exception in function 'spawn':
 Error: spawn zip ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Scheduling process exit
Exiting after uncaught exception in 'spawn':
 Error: spawn zip ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
destroying because of error undefined
`

**Comment by Imperial-Guard** [comment]
Found the issue due to a missing softDeps called zip. I added zip and made a pull request.

**Comment by sapk** [comment]
Closed by your PR #44. Thanks again
